#!/usr/bin/env python3
"""
besimagargun.com page builder. Python 3 standard library only, nothing to install.

Run from anywhere:   python3 tools/build.py

It (re)creates the parts of the site that come from data files:
  * publications/index.html and publications/<slug>/   from data/publications.json (+ data/bib/<slug>.bib)
  * events/index.html and events/<slug>/                from data/talks.json
  * the "Selected Publications" and "Talks" blocks in index.html
  * the Experience / Education / Academic Service / Awards blocks of experience/index.html (copied from index.html)
  * sitemap.xml

Everything else (index.html, experience/index.html, 404.html, assets/) is plain HTML/CSS: edit it directly.
Blocks between <!-- BEGIN:name --> and <!-- END:name --> markers are rewritten by this script.
"""
import datetime
import html
import json
import pathlib
import re
import shutil
import sys
import unicodedata
import urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://besimagargun.com"
OWNER = "Besim Fazil Agargun"
OWNER_ROLE = "Gastroenterology Fellow"
OWNER_PLACE = "Istanbul University, Istanbul Faculty of Medicine"
GENERATED = "<!-- generated by tools/build.py from data/*.json; do not edit by hand -->"
MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]
YEAR = datetime.date.today().year
CV_BLOCKS = ("experience", "education", "service", "awards")


# ---------------------------------------------------------------- helpers
def esc(s):
    return html.escape(str(s), quote=True)


def norm(name):
    s = name.replace("ı", "i").replace("İ", "I")
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c)).lower()
    return " ".join(re.sub(r"[^a-z]", " ", s).split())


OWNER_KEYS = {norm(x) for x in (
    "Besim Fazil Agargun", "Besim F Agargun", "Besim Agargun", "BF Agargun", "B F Agargun",
    "Agargun BF", "Agargun B F", "Agargun Besim Fazil", "Agargun Besim F", "Agargun B")}


def is_owner(name):
    return norm(name) in OWNER_KEYS


def icon(name, root):
    return f'<svg class="icon" aria-hidden="true"><use href="{root}assets/icons.svg#{name}"></use></svg>'


def logo(root):
    return f'<svg class="logo" aria-hidden="true" viewBox="0 0 231 346"><use href="{root}assets/icons.svg#gi"></use></svg>'


def ymd(d):
    y, m, day = (int(x) for x in (d.split("-") + ["1", "1"])[:3])
    return y, m, day


def month_year(d):
    y, m, _ = ymd(d)
    return f"{MONTHS[m - 1]} {y}"


def short_month_year(d):
    y, m, _ = ymd(d)
    return f"{MONTHS[m - 1][:3]} {y}"


def short_date(d):
    y, m, day = ymd(d)
    return f"{MONTHS[m - 1][:3]} {day}, {y}"


def date_range(start, end):
    if not end or end == start:
        return short_date(start)
    y1, m1, d1 = ymd(start)
    y2, m2, d2 = ymd(end)
    if (y1, m1) == (y2, m2):
        return f"{MONTHS[m1 - 1][:3]} {d1}-{d2}, {y1}"
    return f"{short_date(start)} - {short_date(end)}"


def day_range(start, end):
    """Like date_range but without the year (used under a year heading)."""
    _, m1, d1 = ymd(start)
    if not end or end == start:
        return f"{MONTHS[m1 - 1][:3]} {d1}"
    _, m2, d2 = ymd(end)
    if m1 == m2:
        return f"{MONTHS[m1 - 1][:3]} {d1}-{d2}"
    return f"{MONTHS[m1 - 1][:3]} {d1} - {MONTHS[m2 - 1][:3]} {d2}"


def inline_md(s):
    s = esc(s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![*\w])\*(?!\s)(.+?)(?<!\s)\*(?![*\w])", r"<em>\1</em>", s)
    s = re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)", r'<a href="\2" target="_blank" rel="noopener">\1</a>', s)
    return s


def md(text):
    out = []
    for block in re.split(r"\n\s*\n", (text or "").strip()):
        lines = [l.strip() for l in block.strip().split("\n") if l.strip()]
        if not lines:
            continue
        if all(l.startswith(("- ", "* ")) for l in lines):
            out.append("<ul>" + "".join(f"<li>{inline_md(l[2:])}</li>" for l in lines) + "</ul>")
        else:
            out.append(f"<p>{inline_md(' '.join(lines))}</p>")
    return "\n".join(out)


def indent(text, n):
    return "\n".join((" " * n + line) if line else line for line in text.split("\n"))


def clip(text, n=158):
    text = " ".join(str(text).split())
    if len(text) <= n:
        return text
    cut = text[:n].rsplit(" ", 1)[0].rstrip(",;:")
    return cut + "…"


def write(path, text):
    path = ROOT / path
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def jsonld(obj):
    return ('<script type="application/ld+json">\n'
            + json.dumps(obj, ensure_ascii=False, indent=1).replace("</", "<\\/")
            + "\n</script>")


def replace_block(doc, name, content):
    pat = re.compile(r"(<!-- BEGIN:%s -->)(.*?)(<!-- END:%s -->)" % (name, name), re.S)
    if not pat.search(doc):
        sys.exit(f"Marker <!-- BEGIN:{name} --> not found")
    return pat.sub(lambda m: m.group(1) + "\n" + content.rstrip() + "\n" + m.group(3), doc, count=1)


def get_block(doc, name):
    m = re.search(r"<!-- BEGIN:%s -->\n?(.*?)<!-- END:%s -->" % (name, name), doc, re.S)
    if not m:
        sys.exit(f"Marker <!-- BEGIN:{name} --> not found")
    return m.group(1)


def rebase(fragment, prefix):
    """Make relative links in a copied block work from a sub-folder."""
    def fix(m):
        attr, url = m.group(1), m.group(2)
        if re.match(r"^(https?:|mailto:|tel:|data:|#|/|\.\./)", url):
            return m.group(0)
        return f'{attr}="{prefix}{url}"'
    return re.sub(r'\b(href|src|srcset)="([^"]+)"', fix, fragment)


# ---------------------------------------------------------------- page shell
def page(*, root, path, title, description, body, og_type="website", head_extra="", width="wrap"):
    """width: "wrap" (lists, wide pages) or "article" (single publication / talk)."""
    url = f"{SITE}/{path}"
    return f"""<!DOCTYPE html>
<html lang="en" data-root="{root}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{GENERATED}
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="{og_type}">
<meta property="og:site_name" content="{OWNER}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{SITE}/assets/img/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@bfagargun">
<meta name="theme-color" content="#0f172a">
<link rel="icon" href="{root}favicon.ico" sizes="48x48">
<link rel="icon" type="image/png" sizes="32x32" href="{root}assets/img/icon-32.png">
<link rel="apple-touch-icon" href="{root}assets/img/apple-touch-icon.png">
<link rel="preload" href="{root}assets/fonts/source-serif-4-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="{root}assets/fonts/source-sans-3-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="{root}assets/css/site.css">
{head_extra}
</head>
<body>
<main class="{width} page">
<a class="back" href="{root}">{icon('arrow-left', root)}Home</a>
{body}
</main>
<footer class="site-footer {width}">{logo(root)}<span>© <span data-year>{YEAR}</span> {OWNER}</span></footer>
<script src="{root}assets/js/site.js" defer></script>
</body>
</html>
"""


def share_links(url, title, root):
    u, t = urllib.parse.quote(url, safe=""), urllib.parse.quote(title, safe="")
    items = [("x", "Share on X", f"https://x.com/intent/tweet?url={u}&text={t}"),
             ("linkedin", "Share on LinkedIn", f"https://www.linkedin.com/sharing/share-offsite/?url={u}"),
             ("facebook", "Share on Facebook", f"https://www.facebook.com/sharer.php?u={u}"),
             ("whatsapp", "Share on WhatsApp", f"https://wa.me/?text={t}%20{u}"),
             ("at-symbol", "Share by e-mail", f"mailto:?subject={t}&body={u}")]
    new_tab = ' target="_blank" rel="noopener"'
    lis = "".join(f'<li><a href="{esc(h)}"{"" if h.startswith("mailto:") else new_tab}'
                  f' title="{n}" aria-label="{n}">{icon(i, root)}</a></li>' for i, n, h in items)
    return f'<ul class="share"><li class="label">Share</li>{lis}</ul>'


def author_card(root):
    return f"""<aside class="author-card">
    <picture><source srcset="{root}assets/img/me-192.webp" type="image/webp"><img src="{root}assets/img/me-192.jpg" width="64" height="64" alt="{OWNER}" loading="lazy"></picture>
    <div>
      <a class="name" href="{root}">{OWNER}</a>
      <p>{OWNER_ROLE}, {OWNER_PLACE}</p>
    </div>
  </aside>"""


def pager(items, i, kind, title_key="title"):
    newer = items[i - 1] if i > 0 else None
    older = items[i + 1] if i + 1 < len(items) else None
    left = (f'<a class="prev" href="../{newer["slug"]}/"><span class="dir">← Newer</span>'
            f'<span class="t">{esc(newer[title_key])}</span></a>') if newer else "<span></span>"
    right = (f'<a class="next" href="../{older["slug"]}/"><span class="dir">Older →</span>'
             f'<span class="t">{esc(older[title_key])}</span></a>') if older else "<span></span>"
    return f'<nav class="pager" aria-label="More {kind}">{left}{right}</nav>'


def topics(tags, skip=""):
    shown = [t for t in tags if t.lower() != skip.lower()]
    if not shown:
        return ""
    return f'<p class="keywords"><span>Topics</span>{", ".join(esc(t) for t in shown)}</p>'


def facts(rows):
    return '<dl class="facts">' + "".join(f"<dt>{k}</dt><dd>{v}</dd>" for k, v in rows) + "</dl>"


# ---------------------------------------------------------------- publications
def authors_html(authors, short=False):
    names = list(authors)
    shown = list(range(len(names)))
    etal = False
    if short and len(names) > 3:
        idx = next((i for i, a in enumerate(names) if is_owner(a)), None)
        shown = [0, 1, 2]
        if idx is not None and idx > 2:
            shown += [None, idx]
        etal = len(names) > max(i for i in shown if i is not None) + 1
    parts = []
    for i in shown:
        if i is None:
            parts.append("…")
        else:
            a = esc(names[i])
            parts.append(f'<span class="me">{a}</span>' if is_owner(names[i]) else a)
    if etal:
        parts.append("et al.")
    return ", ".join(parts)


def pub_links(p, pub_dir):
    links = []
    if p.get("pmid"):
        links.append(f'<a href="https://pubmed.ncbi.nlm.nih.gov/{esc(p["pmid"])}/" target="_blank" rel="noopener">PubMed</a>')
    links.append(f'<a href="{pub_dir}cite.bib" data-cite>Cite</a>')
    if p.get("doi"):
        links.append(f'<a href="https://doi.org/{esc(p["doi"])}" target="_blank" rel="noopener">DOI</a>')
    return '<p class="pub-links">' + "".join(links) + "</p>"


def pub_item(p, pub_dir, short=False, show_year=True):
    venue = f"<em>{esc(p['journal'])}</em>"
    if show_year:
        venue += f", {ymd(p['date'])[0]}"
    kind = p.get("type", "Journal article")
    if kind != "Journal article":
        venue += f" · {esc(kind)}"
    return (f'<li>\n'
            f'  <a class="pub-title" href="{pub_dir}">{esc(p["title"])}</a>\n'
            f'  <p class="pub-authors">{authors_html(p["authors"], short)}</p>\n'
            f'  <p class="pub-venue">{venue}</p>\n'
            f'  {pub_links(p, pub_dir)}\n'
            f'</li>')


def citation_extra(p, path):
    y, m, _ = ymd(p["date"])
    meta = [f'<meta name="citation_title" content="{esc(p["title"])}">']
    meta += [f'<meta name="citation_author" content="{esc(a)}">' for a in p["authors"]]
    meta.append(f'<meta name="citation_publication_date" content="{y}/{m:02d}">')
    meta.append(f'<meta name="citation_journal_title" content="{esc(p["journal"])}">')
    if p.get("volume"):
        meta.append(f'<meta name="citation_volume" content="{esc(p["volume"])}">')
    if p.get("issue"):
        meta.append(f'<meta name="citation_issue" content="{esc(p["issue"])}">')
    if p.get("pages"):
        first, _, last = p["pages"].partition("-")
        meta.append(f'<meta name="citation_firstpage" content="{esc(first)}">')
        if last:
            meta.append(f'<meta name="citation_lastpage" content="{esc(last)}">')
    if p.get("doi"):
        meta.append(f'<meta name="citation_doi" content="{esc(p["doi"])}">')
    if p.get("pmid"):
        meta.append(f'<meta name="citation_pmid" content="{esc(p["pmid"])}">')
    authors = [{"@type": "Person", "name": a, **({"@id": f"{SITE}/#person"} if is_owner(a) else {})}
               for a in p["authors"]]
    ld = {"@context": "https://schema.org", "@type": "ScholarlyArticle", "name": p["title"],
          "headline": clip(p["title"], 110), "author": authors, "datePublished": f"{y}-{m:02d}",
          "isPartOf": {"@type": "Periodical", "name": p["journal"]}, "url": f"{SITE}/{path}"}
    ids = []
    if p.get("doi"):
        ld["sameAs"] = f"https://doi.org/{p['doi']}"
        ids.append({"@type": "PropertyValue", "propertyID": "DOI", "value": p["doi"]})
    if p.get("pmid"):
        ids.append({"@type": "PropertyValue", "propertyID": "PMID", "value": p["pmid"]})
    if ids:
        ld["identifier"] = ids
    if p.get("abstract"):
        ld["abstract"] = " ".join(p["abstract"].split())
    return "\n".join(meta) + "\n" + jsonld(ld)


def make_bib(p):
    fields = [("author", " and ".join(p["authors"])), ("title", p["title"]), ("journal", p["journal"]),
              ("year", str(ymd(p["date"])[0])), ("volume", p.get("volume", "")), ("number", p.get("issue", "")),
              ("pages", p.get("pages", "").replace("-", "--")), ("doi", p.get("doi", "")), ("pmid", p.get("pmid", ""))]
    body = ",\n".join(f" {k} = {{{v}}}" for k, v in fields if v)
    return f"@article{{{p['slug'].replace('-', '')},\n{body}\n}}\n"


def year_groups(items, render):
    groups = []
    for x in items:
        y = ymd(x["date"])[0]
        if not groups or groups[-1][0] != y:
            groups.append((y, []))
        groups[-1][1].append(x)
    return "\n".join(f'<section class="year-group">\n<h2>{y}</h2>\n{render(xs)}\n</section>' for y, xs in groups)


def build_publications(pubs):
    changed = []
    for i, p in enumerate(pubs):
        path = f"publications/{p['slug']}/"
        root = "../../"
        kind = p.get("type", "Journal article")
        vol = p.get("volume", "")
        if vol:
            vol += f"({p['issue']})" if p.get("issue") else ""
            vol += f":{p['pages']}" if p.get("pages") else ""
        venue = [f"<em>{esc(p['journal'])}</em>", month_year(p["date"])] + ([esc(vol)] if vol else [])
        rows = [("Type", esc(kind)), ("Journal", f"<em>{esc(p['journal'])}</em>"), ("Published", month_year(p["date"]))]
        if vol:
            rows.append(("Volume", esc(vol)))
        if p.get("doi"):
            rows.append(("DOI", f'<a href="https://doi.org/{esc(p["doi"])}" target="_blank" rel="noopener">{esc(p["doi"])}</a>'))
        if p.get("pmid"):
            rows.append(("PMID", f'<a href="https://pubmed.ncbi.nlm.nih.gov/{esc(p["pmid"])}/" target="_blank" rel="noopener">{esc(p["pmid"])}</a>'))
        abstract = (f'<h2>Abstract</h2>\n  <div class="prose">\n{md(p["abstract"])}\n  </div>'
                    if p.get("abstract") else "")
        body = f"""<article>
  <header class="article-head">
    <p class="kicker"><a href="../">Publications</a> · {esc(kind)}</p>
    <h1>{esc(p['title'])}</h1>
    <p class="byline">{authors_html(p['authors'])}</p>
    <p class="venue">{' · '.join(venue)}</p>
    {pub_links(p, '')}
  </header>
  {abstract}
  <h2>Details</h2>
  {facts(rows)}
  {topics(p.get('tags', []), skip=kind)}
  {share_links(SITE + '/' + path, p['title'], root)}
  {author_card(root)}
  {pager(pubs, i, 'publications')}
</article>"""
        if p.get("abstract"):
            desc = clip(p["abstract"])
        else:
            desc = clip(f"{p['title']} {kind} in {p['journal']}, {month_year(p['date'])}. "
                        f"Authors: {', '.join(p['authors'][:4])}{' et al.' if len(p['authors']) > 4 else ''}")
        doc = page(root=root, path=path, title=f"{p['title']} | {OWNER}", description=desc, body=body,
                   og_type="article", head_extra=citation_extra(p, path), width="article")
        if write(path + "index.html", doc):
            changed.append(path)
        bib_src = ROOT / "data" / "bib" / f"{p['slug']}.bib"
        bib = bib_src.read_text(encoding="utf-8") if bib_src.exists() else make_bib(p)
        write(path + "cite.bib", bib)

    groups = year_groups(pubs, lambda xs: '<ol class="pubs">\n'
                         + "\n".join(pub_item(p, f"{p['slug']}/", show_year=False) for p in xs) + "\n</ol>")
    body = f"""<header class="page-head">
  <h1>Publications</h1>
  <p class="intro">{len(pubs)} peer-reviewed publications, newest first. Also on <a href="https://pubmed.ncbi.nlm.nih.gov/?term=Agargun+BF%5BAuthor%5D&amp;sort=date" target="_blank" rel="noopener">PubMed</a>, <a href="https://scholar.google.com/citations?hl=en&amp;user=MeNxgD4AAAAJ" target="_blank" rel="noopener">Google Scholar</a> and <a href="https://orcid.org/0000-0002-3933-1881" target="_blank" rel="noopener">ORCID</a>.</p>
</header>
{groups}"""
    doc = page(root="../", path="publications/", title=f"Publications | {OWNER}",
               description="Peer-reviewed publications of Besim Fazil Agargun (Besim Fazıl Ağargün), MD, in gastroenterology, hepatology, inflammatory bowel disease and endoscopy.",
               body=body)
    if write("publications/index.html", doc):
        changed.append("publications/")
    return changed


# ---------------------------------------------------------------- talks
def talk_item(t, base, when):
    return f"""<li>
  <time datetime="{t['date']}">{when}</time>
  <div>
    <h3><a href="{base}{t['slug']}/">{esc(t['title'])}</a></h3>
    <p class="talk-where">{esc(t['event'])} · {esc(t['location'])}</p>
    <p class="talk-summary">{esc(t['summary'])}</p>
  </div>
</li>"""


def build_talks(talks):
    changed = []
    for i, t in enumerate(talks):
        path = f"events/{t['slug']}/"
        root = "../../"
        event = (f'<a href="{esc(t["event_url"])}" target="_blank" rel="noopener">{esc(t["event"])}</a>'
                 if t.get("event_url") else esc(t["event"]))
        rows = [("Date", date_range(t["date"], t.get("end"))), ("Event", event), ("Location", esc(t["location"]))]
        body = f"""<article>
  <header class="article-head">
    <p class="kicker"><a href="../">Talks</a> · {esc(t['event'])}</p>
    <h1>{esc(t['title'])}</h1>
    <p class="venue">{date_range(t['date'], t.get('end'))} · {esc(t['location'])}</p>
  </header>
  <h2>Summary</h2>
  <div class="prose">
{md(t.get('abstract') or t['summary'])}
  </div>
  <h2>Details</h2>
  {facts(rows)}
  {topics(t.get('tags', []))}
  {share_links(SITE + '/' + path, t['title'], root)}
  {author_card(root)}
  {pager(talks, i, 'talks')}
</article>"""
        doc = page(root=root, path=path, title=f"{t['title']} | {OWNER}", description=clip(t["summary"]),
                   body=body, og_type="article", width="article")
        if write(path + "index.html", doc):
            changed.append(path)
    groups = year_groups(talks, lambda xs: '<ol class="talks">\n'
                         + "\n".join(talk_item(t, "", day_range(t["date"], t.get("end"))) for t in xs) + "\n</ol>")
    body = f"""<header class="page-head">
  <h1>Talks</h1>
  <p class="intro">Oral presentations, moderated posters and session chairing at international congresses.</p>
</header>
{groups}"""
    doc = page(root="../", path="events/", title=f"Talks | {OWNER}",
               description="Talks, oral presentations and moderated posters by Besim Fazil Agargun, MD, at UEG Week, DDW and other international congresses.",
               body=body)
    if write("events/index.html", doc):
        changed.append("events/")
    return changed


# ---------------------------------------------------------------- home page and CV page blocks
def build_blocks(pubs, talks):
    changed = []
    home = (ROOT / "index.html").read_text(encoding="utf-8")
    featured = [p for p in pubs if p.get("featured")]
    sel = ('    <ol class="pubs">\n'
           + indent("\n".join(pub_item(p, f"publications/{p['slug']}/", short=True) for p in featured), 6)
           + "\n    </ol>")
    home = replace_block(home, "selected-publications", sel)
    rec = ('    <ol class="talks">\n'
           + indent("\n".join(talk_item(t, "events/", short_month_year(t["date"])) for t in talks[:3]), 6)
           + "\n    </ol>")
    home = replace_block(home, "recent-talks", rec)
    if write("index.html", home):
        changed.append("index.html")
    cv_path = ROOT / "experience" / "index.html"
    if cv_path.exists():
        cv = cv_path.read_text(encoding="utf-8")
        for name in CV_BLOCKS:
            cv = replace_block(cv, name, rebase(get_block(home, name), "../"))
        if write("experience/index.html", cv):
            changed.append("experience/index.html")
    return changed


# ---------------------------------------------------------------- sitemap and clean-up
def build_sitemap(pubs, talks):
    urls = ["", "experience/", "publications/"] + [f"publications/{p['slug']}/" for p in pubs] \
        + ["events/"] + [f"events/{t['slug']}/" for t in talks]
    body = "\n".join(f"  <url><loc>{SITE}/{u}</loc></url>" for u in urls)
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + "\n</urlset>\n")
    return ["sitemap.xml"] if write("sitemap.xml", xml) else []


def remove_stale(folder, slugs):
    removed = []
    base = ROOT / folder
    if not base.exists():
        return removed
    for d in base.iterdir():
        idx = d / "index.html"
        if d.is_dir() and d.name not in slugs and idx.exists() and GENERATED in idx.read_text(encoding="utf-8"):
            shutil.rmtree(d)
            removed.append(f"{folder}/{d.name}/")
    return removed


def main():
    pubs = json.loads((ROOT / "data" / "publications.json").read_text(encoding="utf-8"))
    talks = json.loads((ROOT / "data" / "talks.json").read_text(encoding="utf-8"))
    for kind, items in (("publication", pubs), ("talk", talks)):
        seen = set()
        for x in items:
            if not re.fullmatch(r"[a-z0-9-]+", x["slug"]):
                sys.exit(f"Bad {kind} slug: {x['slug']!r} (use lowercase letters, digits and -)")
            if x["slug"] in seen:
                sys.exit(f"Duplicate {kind} slug: {x['slug']}")
            seen.add(x["slug"])
    pubs.sort(key=lambda p: (p["date"], p["title"]), reverse=True)
    talks.sort(key=lambda t: t["date"], reverse=True)
    changed = build_publications(pubs) + build_talks(talks) + build_blocks(pubs, talks) + build_sitemap(pubs, talks)
    removed = remove_stale("publications", {p["slug"] for p in pubs}) + remove_stale("events", {t["slug"] for t in talks})
    print(f"{len(pubs)} publications, {len(talks)} talks.")
    print("Updated: " + (", ".join(changed) if changed else "nothing (already up to date)"))
    if removed:
        print("Removed: " + ", ".join(removed))


if __name__ == "__main__":
    main()
