#!/usr/bin/env python3
"""
besimagargun.com page builder. Python 3 standard library only, nothing to install.

Run from anywhere:   python3 tools/build.py

It (re)creates the parts of the site that come from data files:
  * publications/index.html and publications/<slug>/   from data/publications.json (+ data/bib/<slug>.bib)
  * events/index.html and events/<slug>/                from data/talks.json
  * the "Selected Publications" and "Talks" blocks in index.html
  * the Experience / Academic Service / Awards blocks of experience/index.html (copied from index.html)
  * sitemap.xml

Everything else (index.html, experience/index.html, 404.html, assets/) is plain HTML/CSS: edit it directly.
Blocks between <!-- BEGIN:name --> and <!-- END:name --> markers are rewritten by this script.
"""
import datetime
import html
import json
import pathlib
import re
import shutil
import sys
import unicodedata
import urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://besimagargun.com"
OWNER = "Besim Fazil Agargun"
OWNER_ROLE = "Gastroenterology Fellow"
OWNER_BIO = ("Gastroenterology and hepatology fellow at Istanbul University, Istanbul Faculty of Medicine. "
             "My clinical work centres on inflammatory bowel disease and diagnostic and therapeutic endoscopy; "
             "my research combines real-world cohorts with natural-language processing and AI-assisted analytics. "
             "I am also a PhD candidate in clinical trials.")
GENERATED = "<!-- generated by tools/build.py from data/*.json; do not edit by hand -->"
MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]
YEAR = datetime.date.today().year


# ---------------------------------------------------------------- helpers
def esc(s):
    return html.escape(str(s), quote=True)


def norm(name):
    s = name.replace("ı", "i").replace("İ", "I")
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c)).lower()
    return " ".join(re.sub(r"[^a-z]", " ", s).split())


OWNER_KEYS = {norm(x) for x in (
    "Besim Fazil Agargun", "Besim F Agargun", "Besim Agargun", "BF Agargun", "B F Agargun",
    "Agargun BF", "Agargun B F", "Agargun Besim Fazil", "Agargun Besim F", "Agargun B")}


def is_owner(name):
    return norm(name) in OWNER_KEYS


def icon(name, root):
    return f'<svg class="icon" aria-hidden="true"><use href="{root}assets/icons.svg#{name}"></use></svg>'


def ymd(d):
    y, m, day = (int(x) for x in (d.split("-") + ["1", "1"])[:3])
    return y, m, day


def month_year(d):
    y, m, _ = ymd(d)
    return f"{MONTHS[m - 1]} {y}"


def short_date(d):
    y, m, day = ymd(d)
    return f"{MONTHS[m - 1][:3]} {day}, {y}"


def date_range(start, end):
    if not end or end == start:
        return short_date(start)
    y1, m1, d1 = ymd(start)
    y2, m2, d2 = ymd(end)
    if (y1, m1) == (y2, m2):
        return f"{MONTHS[m1 - 1][:3]} {d1}-{d2}, {y1}"
    return f"{short_date(start)} - {short_date(end)}"


def inline_md(s):
    s = esc(s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![*\w])\*(?!\s)(.+?)(?<!\s)\*(?![*\w])", r"<em>\1</em>", s)
    s = re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)", r'<a href="\2" target="_blank" rel="noopener">\1</a>', s)
    return s


def md(text):
    out = []
    for block in re.split(r"\n\s*\n", (text or "").strip()):
        lines = [l.strip() for l in block.strip().split("\n") if l.strip()]
        if not lines:
            continue
        if all(l.startswith(("- ", "* ")) for l in lines):
            out.append("<ul>" + "".join(f"<li>{inline_md(l[2:])}</li>" for l in lines) + "</ul>")
        else:
            out.append(f"<p>{inline_md(' '.join(lines))}</p>")
    return "\n".join(out)


def clip(text, n=158):
    text = " ".join(str(text).split())
    if len(text) <= n:
        return text
    cut = text[:n].rsplit(" ", 1)[0].rstrip(",;:")
    return cut + "…"


def write(path, text):
    path = ROOT / path
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def jsonld(obj):
    return ('<script type="application/ld+json">\n'
            + json.dumps(obj, ensure_ascii=False, indent=1).replace("</", "<\\/")
            + "\n</script>")


def replace_block(doc, name, content):
    pat = re.compile(r"(<!-- BEGIN:%s -->)(.*?)(<!-- END:%s -->)" % (name, name), re.S)
    if not pat.search(doc):
        sys.exit(f"Marker <!-- BEGIN:{name} --> not found")
    return pat.sub(lambda m: m.group(1) + "\n" + content.rstrip() + "\n" + m.group(3), doc, count=1)


def get_block(doc, name):
    m = re.search(r"<!-- BEGIN:%s -->\n?(.*?)<!-- END:%s -->" % (name, name), doc, re.S)
    if not m:
        sys.exit(f"Marker <!-- BEGIN:{name} --> not found")
    return m.group(1)


def rebase(fragment, prefix):
    """Make relative links in a copied block work from a sub-folder."""
    def fix(m):
        attr, url = m.group(1), m.group(2)
        if re.match(r"^(https?:|mailto:|tel:|data:|#|/|\.\./)", url):
            return m.group(0)
        return f'{attr}="{prefix}{url}"'
    return re.sub(r'\b(href|src|srcset)="([^"]+)"', fix, fragment)


# ---------------------------------------------------------------- page shell
def page(*, root, path, title, description, body, og_type="website", head_extra=""):
    url = f"{SITE}/{path}"
    return f"""<!DOCTYPE html>
<html lang="en" data-root="{root}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{GENERATED}
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="{og_type}">
<meta property="og:site_name" content="Besim Fazil Agargun">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{SITE}/assets/img/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@bfagargun">
<meta name="theme-color" content="#0f172a">
<link rel="icon" href="{root}favicon.ico" sizes="48x48">
<link rel="icon" type="image/png" sizes="32x32" href="{root}assets/img/icon-32.png">
<link rel="apple-touch-icon" href="{root}assets/img/apple-touch-icon.png">
<link rel="stylesheet" href="{root}assets/css/site.css">
{head_extra}
</head>
<body>
<a class="home-link" href="{root}">{icon('arrow-left', root)}Home</a>
<main>
{body}
</main>
<footer class="site-footer">© <span data-year>{YEAR}</span> Besim Fazil Agargun</footer>
<script src="{root}assets/js/site.js" defer></script>
</body>
</html>
"""


def share_links(url, title, root):
    u, t = urllib.parse.quote(url, safe=""), urllib.parse.quote(title, safe="")
    items = [("x", "X", f"https://x.com/intent/tweet?url={u}&text={t}"),
             ("facebook", "Facebook", f"https://www.facebook.com/sharer.php?u={u}"),
             ("at-symbol", "E-mail", f"mailto:?subject={t}&body={u}"),
             ("linkedin", "LinkedIn", f"https://www.linkedin.com/sharing/share-offsite/?url={u}"),
             ("whatsapp", "WhatsApp", f"https://wa.me/?text={t}%20{u}")]
    lis = "".join(f'<li><a href="{esc(h)}" target="_blank" rel="noopener" title="Share on {n}" aria-label="Share on {n}">{icon(i, root)}</a></li>'
                  for i, n, h in items)
    return f'<ul class="share"><li class="label">Share</li>{lis}</ul>'


def author_card(root):
    return f"""<aside class="author-card">
  <picture><source srcset="{root}assets/img/me-192.webp" type="image/webp"><img src="{root}assets/img/me-192.jpg" width="96" height="96" alt="{OWNER}" loading="lazy"></picture>
  <div>
    <a class="name" href="{root}">{OWNER}</a>
    <p class="role">{OWNER_ROLE}</p>
    <p>{esc(OWNER_BIO)}</p>
  </div>
</aside>"""


def pager(items, i, kind, title_key="title"):
    newer = items[i - 1] if i > 0 else None
    older = items[i + 1] if i + 1 < len(items) else None
    left = (f'<a class="prev" href="../{newer["slug"]}/"><span class="dir">← Newer</span>'
            f'<span class="t">{esc(newer[title_key])}</span></a>') if newer else "<span></span>"
    right = (f'<a class="next" href="../{older["slug"]}/"><span class="dir">Older →</span>'
             f'<span class="t">{esc(older[title_key])}</span></a>') if older else "<span></span>"
    return f'<nav class="pager" aria-label="More {kind}">{left}{right}</nav>'


# ---------------------------------------------------------------- publications
def authors_html(authors, short=False):
    names = list(authors)
    shown = list(range(len(names)))
    etal = False
    if short and len(names) > 3:
        idx = next((i for i, a in enumerate(names) if is_owner(a)), None)
        shown = [0, 1, 2]
        if idx is not None and idx > 2:
            shown += [None, idx]
        etal = len(names) > max(i for i in shown if i is not None) + 1
    parts = []
    for i in shown:
        if i is None:
            parts.append("…")
        else:
            a = esc(names[i])
            parts.append(f'<span class="me">{a}</span>' if is_owner(names[i]) else a)
    if etal:
        parts.append("et al.")
    return ", ".join(parts)


def pub_links(p, root, pub_dir):
    links = []
    if p.get("pmid"):
        links.append(f'<a href="https://pubmed.ncbi.nlm.nih.gov/{esc(p["pmid"])}/" target="_blank" rel="noopener">{icon("link", root)}PubMed</a>')
    links.append(f'<a href="{pub_dir}cite.bib" data-cite>{icon("document-duplicate", root)}Cite</a>')
    if p.get("doi"):
        links.append(f'<a href="https://doi.org/{esc(p["doi"])}" target="_blank" rel="noopener">{icon("link", root)}DOI</a>')
    return '<div class="pub-links">' + "".join(links) + "</div>"


def pub_item(p, root, pub_dir, short=False):
    year = ymd(p["date"])[0]
    return (f'<li class="pub"><span class="authors">{authors_html(p["authors"], short)}</span> ({year}). '
            f'<a class="title" href="{pub_dir}">{esc(p["title"])}</a>{"" if p["title"].rstrip().endswith((".", "?", "!")) else "."} '
            f'<span class="journal">{esc(p["journal"])}</span>.'
            f'{pub_links(p, root, pub_dir)}</li>')


def citation_extra(p, path):
    y, m, _ = ymd(p["date"])
    meta = [f'<meta name="citation_title" content="{esc(p["title"])}">']
    meta += [f'<meta name="citation_author" content="{esc(a)}">' for a in p["authors"]]
    meta.append(f'<meta name="citation_publication_date" content="{y}/{m:02d}">')
    meta.append(f'<meta name="citation_journal_title" content="{esc(p["journal"])}">')
    if p.get("volume"):
        meta.append(f'<meta name="citation_volume" content="{esc(p["volume"])}">')
    if p.get("issue"):
        meta.append(f'<meta name="citation_issue" content="{esc(p["issue"])}">')
    if p.get("pages"):
        first, _, last = p["pages"].partition("-")
        meta.append(f'<meta name="citation_firstpage" content="{esc(first)}">')
        if last:
            meta.append(f'<meta name="citation_lastpage" content="{esc(last)}">')
    if p.get("doi"):
        meta.append(f'<meta name="citation_doi" content="{esc(p["doi"])}">')
    if p.get("pmid"):
        meta.append(f'<meta name="citation_pmid" content="{esc(p["pmid"])}">')
    authors = [{"@type": "Person", "name": a, **({"@id": f"{SITE}/#person"} if is_owner(a) else {})}
               for a in p["authors"]]
    ld = {"@context": "https://schema.org", "@type": "ScholarlyArticle", "name": p["title"],
          "headline": clip(p["title"], 110), "author": authors, "datePublished": f"{y}-{m:02d}",
          "isPartOf": {"@type": "Periodical", "name": p["journal"]}, "url": f"{SITE}/{path}"}
    ids = []
    if p.get("doi"):
        ld["sameAs"] = f"https://doi.org/{p['doi']}"
        ids.append({"@type": "PropertyValue", "propertyID": "DOI", "value": p["doi"]})
    if p.get("pmid"):
        ids.append({"@type": "PropertyValue", "propertyID": "PMID", "value": p["pmid"]})
    if ids:
        ld["identifier"] = ids
    if p.get("abstract"):
        ld["abstract"] = " ".join(p["abstract"].split())
    return "\n".join(meta) + "\n" + jsonld(ld)


def make_bib(p):
    fields = [("author", " and ".join(p["authors"])), ("title", p["title"]), ("journal", p["journal"]),
              ("year", str(ymd(p["date"])[0])), ("volume", p.get("volume", "")), ("number", p.get("issue", "")),
              ("pages", p.get("pages", "").replace("-", "--")), ("doi", p.get("doi", "")), ("pmid", p.get("pmid", ""))]
    body = ",\n".join(f" {k} = {{{v}}}" for k, v in fields if v)
    return f"@article{{{p['slug'].replace('-', '')},\n{body}\n}}\n"


def build_publications(pubs):
    changed = []
    for i, p in enumerate(pubs):
        path = f"publications/{p['slug']}/"
        root = "../../"
        venue = [f"<em>{esc(p['journal'])}</em>", month_year(p["date"])]
        vol = p.get("volume", "")
        if vol:
            vol += f"({p['issue']})" if p.get("issue") else ""
            vol += f":{p['pages']}" if p.get("pages") else ""
            venue.append(esc(vol))
        details = [("Type", esc(p.get("type", "Journal article"))), ("Journal", esc(p["journal"])),
                   ("Published", month_year(p["date"]))]
        if vol:
            details.append(("Volume", esc(vol)))
        if p.get("doi"):
            details.append(("DOI", f'<a href="https://doi.org/{esc(p["doi"])}" target="_blank" rel="noopener">{esc(p["doi"])}</a>'))
        if p.get("pmid"):
            details.append(("PMID", f'<a href="https://pubmed.ncbi.nlm.nih.gov/{esc(p["pmid"])}/" target="_blank" rel="noopener">{esc(p["pmid"])}</a>'))
        dl = "".join(f"<dt>{k}</dt><dd>{v}</dd>" for k, v in details)
        abstract = f'<h2>Abstract</h2>\n<div class="abstract">\n{md(p["abstract"])}\n</div>' if p.get("abstract") else ""
        tags = ("<ul class=\"tags\">" + "".join(f"<li>{esc(t)}</li>" for t in p.get("tags", [])) + "</ul>") if p.get("tags") else ""
        body = f"""<article class="article">
  <p class="kicker"><a href="../">Publications</a><span aria-hidden="true">·</span><span>{esc(p.get('type', 'Journal article'))}</span></p>
  <h1>{esc(p['title'])}</h1>
  <p class="byline">{authors_html(p['authors'])}</p>
  <p class="venue">{' · '.join(venue)}</p>
  {pub_links(p, root, '')}
  {abstract}
  <h2>Details</h2>
  <dl class="details">{dl}</dl>
  {tags}
  {share_links(SITE + '/' + path, p['title'], root)}
  {author_card(root)}
  {pager(pubs, i, 'publications')}
</article>"""
        if p.get("abstract"):
            desc = clip(p["abstract"])
        else:
            desc = clip(f"{p['title']} {p.get('type', 'Article')} in {p['journal']}, {month_year(p['date'])}. "
                        f"Authors: {', '.join(p['authors'][:4])}{' et al.' if len(p['authors']) > 4 else ''}")
        doc = page(root=root, path=path, title=f"{p['title']} | {OWNER}", description=desc, body=body,
                   og_type="article", head_extra=citation_extra(p, path))
        if write(path + "index.html", doc):
            changed.append(path)
        bib_src = ROOT / "data" / "bib" / f"{p['slug']}.bib"
        bib = bib_src.read_text(encoding="utf-8") if bib_src.exists() else make_bib(p)
        write(path + "cite.bib", bib)

    # list page, grouped by year
    groups = []
    for p in pubs:
        y = ymd(p["date"])[0]
        if not groups or groups[-1][0] != y:
            groups.append((y, []))
        groups[-1][1].append(p)
    parts = []
    for y, items in groups:
        parts.append(f'<h2 class="year-head">{y}</h2>\n<ol class="pub-list">\n'
                     + "\n".join(pub_item(p, "../", f"{p['slug']}/") for p in items) + "\n</ol>")
    body = f"""<header class="page-head container">
  <h1>Publications</h1>
  <p>{len(pubs)} peer-reviewed publications. Also on <a href="https://pubmed.ncbi.nlm.nih.gov/?term=Agargun+BF%5BAuthor%5D&amp;sort=date" target="_blank" rel="noopener">PubMed</a>, <a href="https://scholar.google.com/citations?hl=en&amp;user=MeNxgD4AAAAJ" target="_blank" rel="noopener">Google Scholar</a> and <a href="https://orcid.org/0000-0002-3933-1881" target="_blank" rel="noopener">ORCID</a>.</p>
</header>
<div class="page-body narrow">
{chr(10).join(parts)}
</div>"""
    doc = page(root="../", path="publications/", title=f"Publications | {OWNER}",
               description=f"Peer-reviewed publications of Besim Fazil Agargun (Besim Fazıl Ağargün), MD, in gastroenterology, hepatology, inflammatory bowel disease and endoscopy.",
               body=body)
    if write("publications/index.html", doc):
        changed.append("publications/")
    return changed


# ---------------------------------------------------------------- talks
def talk_item(t, root, base):
    return f"""<li class="talk">
  <time datetime="{t['date']}">{short_date(t['date'])}</time>
  <div>
    <h3><a href="{base}{t['slug']}/">{esc(t['title'])}</a></h3>
    <p class="where">{esc(t['event'])} · {esc(t['location'])}</p>
    <p class="summary">{esc(t['summary'])}</p>
    <a class="read-more" href="{base}{t['slug']}/">Read more {icon('chevron-right', root)}</a>
  </div>
</li>"""


def talk_jsonld(t, path):
    """Complete schema.org Event so Search Console reports no missing fields
    (address, offers, image, eventStatus, organizer, performer)."""
    address = {"@type": "PostalAddress", "addressLocality": t.get("city") or t["location"].split(",")[0].strip()}
    if t.get("region"):
        address["addressRegion"] = t["region"]
    if t.get("country"):
        address["addressCountry"] = t["country"]
    place = {"@type": "Place", "name": t.get("venue") or t["location"], "address": address}
    ld = {"@context": "https://schema.org", "@type": "Event", "name": t["title"],
          "description": " ".join(t["summary"].split()), "url": f"{SITE}/{path}",
          "startDate": t["date"], "endDate": t.get("end") or t["date"],
          "eventStatus": "https://schema.org/EventScheduled",
          "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
          "location": place, "image": [f"{SITE}/assets/img/og.png"],
          "performer": {"@type": "Person", "@id": f"{SITE}/#person", "name": OWNER},
          "superEvent": {"@type": "Event", "name": t["event"], "url": t.get("event_url", ""), "location": place},
          "offers": {"@type": "Offer", "url": t.get("event_url") or f"{SITE}/{path}",
                     "availability": "https://schema.org/InStock", "validFrom": t["date"][:4] + "-01-01"}}
    if not t.get("event_url"):
        del ld["superEvent"]["url"]
    if t.get("organizer"):
        org = {"@type": "Organization", "name": t["organizer"]}
        if t.get("organizer_url"):
            org["url"] = t["organizer_url"]
        ld["organizer"] = org
    return jsonld(ld)


def build_talks(talks):
    changed = []
    for i, t in enumerate(talks):
        path = f"events/{t['slug']}/"
        root = "../../"
        event = (f'<a href="{esc(t["event_url"])}" target="_blank" rel="noopener">{esc(t["event"])}</a>'
                 if t.get("event_url") else esc(t["event"]))
        details = [("Date", date_range(t["date"], t.get("end"))), ("Event", event), ("Location", esc(t["location"]))]
        dl = "".join(f"<dt>{k}</dt><dd>{v}</dd>" for k, v in details)
        tags = ("<ul class=\"tags\">" + "".join(f"<li>{esc(x)}</li>" for x in t.get("tags", [])) + "</ul>") if t.get("tags") else ""
        body = f"""<article class="article">
  <p class="kicker"><a href="../">Talks</a><span aria-hidden="true">·</span><span>{esc(t['event'])}</span></p>
  <h1>{esc(t['title'])}</h1>
  <p class="venue">{date_range(t['date'], t.get('end'))} · {esc(t['location'])}</p>
  <h2>Summary</h2>
  <div class="abstract">
{md(t.get('abstract') or t['summary'])}
  </div>
  <h2>Details</h2>
  <dl class="details">{dl}</dl>
  {tags}
  {share_links(SITE + '/' + path, t['title'], root)}
  {author_card(root)}
  {pager(talks, i, 'talks')}
</article>"""
        doc = page(root=root, path=path, title=f"{t['title']} | {OWNER}", description=clip(t["summary"]),
                   body=body, og_type="article", head_extra=talk_jsonld(t, path))
        if write(path + "index.html", doc):
            changed.append(path)
    body = f"""<header class="page-head container">
  <h1>Talks</h1>
  <p>Oral presentations, moderated posters and session chairing at international congresses.</p>
</header>
<div class="page-body narrow">
<ol class="talk-list">
{chr(10).join(talk_item(t, '../', '') for t in talks)}
</ol>
</div>"""
    doc = page(root="../", path="events/", title=f"Talks | {OWNER}",
               description="Talks, oral presentations and moderated posters by Besim Fazil Agargun, MD, at UEG Week, DDW and other international congresses.",
               body=body)
    if write("events/index.html", doc):
        changed.append("events/")
    return changed


# ---------------------------------------------------------------- home page and CV page blocks
def build_blocks(pubs, talks):
    changed = []
    home_path = ROOT / "index.html"
    home = home_path.read_text(encoding="utf-8")
    featured = [p for p in pubs if p.get("featured")]
    sel = '<ol class="pub-list">\n' + "\n".join(pub_item(p, "", f"publications/{p['slug']}/", short=True) for p in featured) + "\n</ol>"
    home = replace_block(home, "selected-publications", sel)
    rec = '<ol class="talk-list">\n' + "\n".join(talk_item(t, "", "events/") for t in talks[:3]) + "\n</ol>"
    home = replace_block(home, "recent-talks", rec)
    if write("index.html", home):
        changed.append("index.html")
    cv_path = ROOT / "experience" / "index.html"
    if cv_path.exists():
        cv = cv_path.read_text(encoding="utf-8")
        for name in ("experience", "service", "awards"):
            cv = replace_block(cv, name, rebase(get_block(home, name), "../"))
        if write("experience/index.html", cv):
            changed.append("experience/index.html")
    return changed


# ---------------------------------------------------------------- sitemap and clean-up
def build_sitemap(pubs, talks):
    urls = ["", "experience/", "publications/"] + [f"publications/{p['slug']}/" for p in pubs] \
        + ["events/"] + [f"events/{t['slug']}/" for t in talks]
    body = "\n".join(f"  <url><loc>{SITE}/{u}</loc></url>" for u in urls)
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + "\n</urlset>\n")
    return ["sitemap.xml"] if write("sitemap.xml", xml) else []


def remove_stale(folder, slugs):
    removed = []
    base = ROOT / folder
    if not base.exists():
        return removed
    for d in base.iterdir():
        idx = d / "index.html"
        if d.is_dir() and d.name not in slugs and idx.exists() and GENERATED in idx.read_text(encoding="utf-8"):
            shutil.rmtree(d)
            removed.append(f"{folder}/{d.name}/")
    return removed


def main():
    pubs = json.loads((ROOT / "data" / "publications.json").read_text(encoding="utf-8"))
    talks = json.loads((ROOT / "data" / "talks.json").read_text(encoding="utf-8"))
    for kind, items in (("publication", pubs), ("talk", talks)):
        seen = set()
        for x in items:
            if not re.fullmatch(r"[a-z0-9-]+", x["slug"]):
                sys.exit(f"Bad {kind} slug: {x['slug']!r} (use lowercase letters, digits and -)")
            if x["slug"] in seen:
                sys.exit(f"Duplicate {kind} slug: {x['slug']}")
            seen.add(x["slug"])
    pubs.sort(key=lambda p: (p["date"], p["title"]), reverse=True)
    talks.sort(key=lambda t: t["date"], reverse=True)
    changed = build_publications(pubs) + build_talks(talks) + build_blocks(pubs, talks) + build_sitemap(pubs, talks)
    removed = remove_stale("publications", {p["slug"] for p in pubs}) + remove_stale("events", {t["slug"] for t in talks})
    print(f"{len(pubs)} publications, {len(talks)} talks.")
    print("Updated: " + (", ".join(changed) if changed else "nothing (already up to date)"))
    if removed:
        print("Removed: " + ", ".join(removed))


if __name__ == "__main__":
    main()
